services:
  # -----------------------
  # MongoDB
  # -----------------------
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

  # -----------------------
  # RabbitMQ
  # -----------------------
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"  # AMQP protocol
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-securepassword}
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3

  # -----------------------
  # Auth Service
  # -----------------------
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "${AUTH_PORT}:8001"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_DAYS=${JWT_EXPIRE_DAYS}
    depends_on:
      mongodb:
        condition: service_healthy

  # -----------------------
  # Todo Service
  # -----------------------
  todo_service:
    build: ./todo_service
    container_name: todo_service
    ports:
      - "${TODO_PORT}:8002"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # -----------------------
  # Analytics Service
  # -----------------------
  analytics_service:
    build: ./analytics_service
    container_name: analytics_service
    ports:
      - "${ANALYTICS_PORT}:8003"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672/
    depends_on:
      mongodb:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # -----------------------
  # Frontend (Nginx)
  # -----------------------
  frontend:
    build: ./frontend_complete
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    environment:
      - VITE_AUTH_URL=${VITE_AUTH_URL}
      - VITE_TODO_URL=${VITE_TODO_URL}
      - VITE_ANALYTICS_URL=${VITE_ANALYTICS_URL}
    depends_on:
      auth_service:
        condition: service_started
      todo_service:
        condition: service_started
      analytics_service:
        condition: service_started

volumes:
  mongo_data:
  rabbitmq_data:
  rabbitmq_logs: