version: "3.9"

services:
  # -----------------------
  # MongoDB
  # -----------------------
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # -----------------------
  # Auth Service
  # -----------------------
  auth_service:
    build: ./auth_service
    container_name: auth_service
    ports:
      - "${AUTH_PORT}:8001"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_DAYS=${JWT_EXPIRE_DAYS}
    depends_on:
      - mongodb

  # -----------------------
  # Todo Service
  # -----------------------
  todo_service:
    build: ./todo_service
    container_name: todo_service
    ports:
      - "${TODO_PORT}:8002"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb

  # -----------------------
  # Analytics Service
  # -----------------------
  analytics_service:
    build: ./analytics_service
    container_name: analytics_service
    ports:
      - "${ANALYTICS_PORT}:8003"
    env_file:
      - .env
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb

  # -----------------------
  # Frontend (Nginx)
  # -----------------------
  frontend:
    build: ./frontend_complete
    container_name: frontend
    ports:
      - "${FRONTEND_PORT}:80"
    env_file:
      - .env
    environment:
      - VITE_AUTH_URL=${VITE_AUTH_URL}
      - VITE_TODO_URL=${VITE_TODO_URL}
      - VITE_ANALYTICS_URL=${VITE_ANALYTICS_URL}
    depends_on:
      - auth_service
      - todo_service
      - analytics_service

volumes:
  mongo_data:
